---
:concurrency: <%= ENV['SIDEKIQ_WORKERS'] %>
staging:
  :concurrency: <%= ENV['SIDEKIQ_WORKERS'] %>
production:
  :concurrency: <%= ENV['SIDEKIQ_WORKERS'] %>
:queues:
 - critical
 - default
 - low
 - mailers
